### ISSUE TITLE
Add android permissions

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-xml#2]
# How can I add android permissions.

Error Code:
        1
Output:
        C:\git\pos.cordova\platforms\android\build\intermediates\res\armv7\debug\xml\config.xml:24: error: Error parsing XML: unbound prefix

``` js
        .pipe(xml([
                '<allow-navigation href="*://ecapp.ptpos.com/*" />',
                '<feature name="http://api.phonegap.com/1.0/file" />', 
                '<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />'
        ]))
```

**Comment by SamVerschueren** [comment]
Hi Robert

Can you copy paste your config.xml file? I think the gulp code is fine, it seems something is wrong in the generated config file.

Thanks,
Sam

**Comment by SamVerschueren** [comment]
Alright, I know what the problem is. It's because the `android:` prefix so it should be possible add an xml namespace to the config.xml file. I added an issue https://github.com/SamVerschueren/cordova-config/issues/8 and will get back to you.

**Comment by mackbrowne** [comment]
Also having this problem, I've tracked the issue back to cordova-config aswell.  not sure what the fix is....

**Comment by SamVerschueren** [comment]
@robertbaker Any suggestions on how we might implement this?

Couple of suggestions
1. Create a new plugin `gulp-cordova-namespace` that allows you to easily add predefined (or custom) namespaces to the `widget` tag
2. Automatically detect the namespaces being used and add them to the `widget` tag

**1** would be the easiest way in development perspective (for me/us), but **2** might be the easiest way for the user.

A `gulp-cordova-permission` plugin would be nice as well I guess.

**Comment by ghost** [comment]
@SamVerschueren I'm thinking option 2. If the namespaces follow a `namespace:keyname` format, it would be easy to detect and negate the need for a seperate plugin. The xml plugin could accept a namespaces array if that proves to be difficult.

gulp-cordova-permission would be nice, it depends on how iOS permissions are declared.

It would be nice to just specify the permissions needed without writing the entire xml element.

**Comment by SamVerschueren** [comment]
Not to shabby on the namespace array. If option **2** seems to difficult, I will go for a separate plugin. The idea behind `gulp-cordova` is small easy-to-use plugins that each do their own thing.

**Comment by SamVerschueren** [comment]
By the way, isn't the plugin adding the permission automatically? Most plugins do that. Not sure if one would want to add a permission himself.

**Comment by ghost** [comment]
That's correct, forgot about that. Plugins declare permissions.

**Comment by SamVerschueren** [comment]
So let's keep this issue open until another use-case pops up where someone wants to use a namespace.

**Comment by ghost** [comment]
I'm having this same issue in a current project.  This is an important use case, given that people are getting around it by creating native plugins to add specific permissions needed by... other native plugins.

**Comment by SamVerschueren** [comment]
But the plugins should define their permissions, no? Why do you need this manually?

**Comment by ghost** [comment]
Yes plugins need to define the permissions they need.

**Comment by ghost** [comment]
I add a Cordova Plugin for media capture (cordova-plugin-media-capture), and that doesn't add the permissions needed to actually get the device audio.

I had to add another plugin - cordova-opentok-android-permissions - to get the MODIFY_AUDIO_SETTINGS permission added to the final build.  Without it, RECORD_AUDIO did not work...  I was not able to get a microphone from the device.

The cordova-plugin-media-capture plugin is not asking for the MODIFY_AUDIO_SETTINGS permission that is required:  https://github.com/apache/cordova-plugin-media-capture/blob/master/plugin.xml

I was lucky enough to be able to solve this by importing another plugin that added these permissions.  Forking the plugin on GitHub and adding MODIFY_AUDIO_SETTINGS permission myself was another option I didn't think of until today.

**Comment by ghost** [comment]
You should file an issue for those plugins. I went through something
similar. The plugin itself must declare the permissions. This tool can't do
that, won't work.

**Comment by SamVerschueren** [comment]
Thanks @robertbaker for chiming in on this. You're right, the plugin itself must define the permissions.
